version: '2'
services:
  gameservice:
    build:
      context: .
      dockerfile: Dockerfile.gameservice
    ports:
      - "8090:8090"
  matchmaker:
    build:
      context: .
      dockerfile: Dockerfile.matchmaker
    ports:
      - "8080:8080"
    depends_on:
      - gameservice
    environment:
      - GAME_SERVER_ADDR=gameservice:8090
    command: [ "/bin/bash", "-c", "wait-for-it $${GAME_SERVER_ADDR} -t 50 -- java -jar -DgameServerAddress=\"$${GAME_SERVER_ADDR}\" /bin/matchmaker*.jar" ]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:8080"
    depends_on:
      - gameservice
      - matchmaker