version: '2'
services:
  game_server:
    build:
      context: .
      dockerfile: Dockerfile.game_server
    ports:
      - "8090:8090"
  matchmaker:
    build:
      context: .
      dockerfile: Dockerfile.matchmaker
    ports:
      - "8080:8080"
    depends_on:
      - game_server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8000:8080"
    depends_on:
      - game_server
      - matchmaker